name: Test My Library locally

on: 
  workflow_dispatch: # This gives you a "Run" button in the UI

jobs:
  call-local-library:
    # Since it's in the same repo, you just point to the file path
    uses: ./.github/workflows/say-hello.yml 
    with:
      username: "Bro"
