# This replaces your vars/sayHello.groovy
name: Shared Library Helper

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Run Greeting
        run: echo "Hello ${{ inputs.name }}, this is from the shared library!"
